### Com base nos dados do seu estado que podem ser acessados nessa [pasta](https://drive.google.com/drive/folders/1EwlrR1DM3TfiDm4bzz98OVwsjwsV3Slk?usp=sharing), calcular a média das temperaturas dos dados e retire uma amostra de 3 colunas (a sua escolha) e 100 linhas, os dados não podem ter campos nulos

In [ ]:
import pandas as pd

In [ ]:
df_PE = pd.read_csv('data_sample_PE.csv', sep = ';')

In [ ]:
df_PE.head()

,Data,Hora UTC,PRECIPITAO TOTAL. HORARIO (mm),PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO. HORARIA (mB),PRESSAO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSAO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m2),TEMPERATURA DO AR - BULBO SECO. HORARIA (C),TEMPERATURA DO PONTO DE ORVALHO (C),TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C),...,VENTO. RAJADA MAXIMA (m/s),VENTO. VELOCIDADE HORARIA (m/s),REGIAO,UF,ESTACAO,CODIGO (WMO),LATITUDE,LONGITUDE,ALTITUDE,DATA DE FUNDACAO
0,2021/04/26,1700 UTC,NaN,971.9,972.9,971.9,1652.5,33.6,15.4,33.6,...,7.4,4.0,NE,PE,FLORESTA,A351,-8.598889,-38.584167,327.42,15/09/08
1,2022/03/02,0900 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NE,PE,FLORESTA,A351,-8.598889,-38.584167,327.42,15/09/08
2,2020/01/30,1200 UTC,0.0,958.8,958.8,958.6,2278.0,26.7,15.8,27.0,...,7.3,2.9,NE,PE,SERRA TALHADA,A350,-7.954277,-38.295082,499.02,09/07/08
3,2020/09/12,0600 UTC,0.0,958.4,958.5,958.3,NaN,19.0,12.2,19.6,...,7.0,2.7,NE,PE,SERRA TALHADA,A350,-7.954277,-38.295082,499.02,09/07/08
4,2020/08/16,1100 UTC,0.0,978.8,978.8,977.9,1372.8,24.6,16.6,24.6,...,4.6,1.9,NE,PE,FLORESTA,A351,-8.598785,-38.584062,327.42,15/09/08

In [ ]:
df_PE[['TEMPERATURA DO AR - BULBO SECO. HORARIA (C)',
    'TEMPERATURA DO PONTO DE ORVALHO (C)',
    'TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C)',
    'TEMPERATURA MINIMA NA HORA ANT. (AUT) (C)',
    'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (C)',
    'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (C)']].mean(numeric_only=True)

TEMPERATURA DO AR - BULBO SECO. HORARIA (C)        25.283303
TEMPERATURA DO PONTO DE ORVALHO (C)                17.382828
TEMPERATURA MAXIMA NA HORA ANT. (AUT) (C)          25.928051
TEMPERATURA MINIMA NA HORA ANT. (AUT) (C)          24.624803
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (C)    17.929704
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (C)    16.852035
dtype: float64

Bônus

In [ ]:
df_PE.loc[3:102,['ESTACAO',
       'ALTITUDE',
       'Hora UTC']]

           ESTACAO  ALTITUDE  Hora UTC
3    SERRA TALHADA    499.02  0600 UTC
4         FLORESTA    327.42  1100 UTC
5        SALGUEIRO    447.00  0200 UTC
6         IBIMIRIM    434.23  1900 UTC
7        PETROLINA    372.72  1600 UTC
..             ...       ...       ...
98         CARUARU    852.00  1800 UTC
99      ARCO VERDE    683.95  0200 UTC
100      GARANHUNS    827.78  1700 UTC
101      SALGUEIRO    447.00  0800 UTC
102       OURICURI    457.85  0900 UTC

[100 rows x 3 columns]

In [ ]:
df_PE.loc[3:102,['ESTACAO',
       'ALTITUDE',
       'Hora UTC']].isnull()

     ESTACAO  ALTITUDE  Hora UTC
3      False     False     False
4      False     False     False
5      False     False     False
6      False     False     False
7      False     False     False
..       ...       ...       ...
98     False     False     False
99     False     False     False
100    False     False     False
101    False     False     False
102    False     False     False

[100 rows x 3 columns]

In [ ]:
df_PE.loc[3:102,['ESTACAO',
       'ALTITUDE',
       'Hora UTC']].isnull().sum()

ESTACAO     0
ALTITUDE    0
Hora UTC    0
dtype: int64

In [ ]:
df_PE_notnull = df_PE.dropna(subset=['ESTACAO', 'ALTITUDE', 'Hora UTC'])

# Selecionar as linhas de 3 a 102
df_PE_notnull = df_PE_notnull.iloc[3:103]

# Verificar a forma do DataFrame resultante
print(df_PE_notnull.shape)

(100, 27)